controller_list:
  - name: fake_left_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - jL5S1_rotx
      - jL5S1_roty
      - jL4L3_rotx
      - jL4L3_roty
      - jL1T12_rotx
      - jL1T12_roty
      - jT9T8_rotx
      - jT9T8_roty
      - jT9T8_rotz
      - jLeftC7Shoulder_rotx
      - jLeftShoulder_rotx
      - jLeftShoulder_roty
      - jLeftShoulder_rotz
      - jLeftElbow_roty
      - jLeftElbow_rotz
      - jLeftWrist_rotx
      - jLeftWrist_rotz
  - name: fake_right_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - jRightC7Shoulder_rotx
      - jRightShoulder_rotx
      - jRightShoulder_roty
      - jRightShoulder_rotz
      - jRightElbow_roty
      - jRightElbow_rotz
      - jRightWrist_rotx
      - jRightWrist_rotz
  - name: fake_right_leg_controller
    type: $(arg fake_execution_type)
    joints:
      - jRightHip_rotx
      - jRightHip_roty
      - jRightHip_rotz
      - jRightKnee_roty
      - jRightKnee_rotz
      - jRightAnkle_rotx
      - jRightAnkle_roty
      - jRightAnkle_rotz
      - jRightBallFoot_roty
  - name: fake_left_leg_controller
    type: $(arg fake_execution_type)
    joints:
      - jLeftHip_rotx
      - jLeftHip_roty
      - jLeftHip_rotz
      - jLeftKnee_roty
      - jLeftKnee_rotz
      - jLeftAnkle_rotx
      - jLeftAnkle_roty
      - jLeftAnkle_rotz
      - jLeftBallFoot_roty
  - name: fake_body_controller
    type: $(arg fake_execution_type)
    joints:
      - jL5S1_rotx
      - jL5S1_roty
      - jL4L3_rotx
      - jL4L3_roty
      - jL1T12_rotx
      - jL1T12_roty
      - jT9T8_rotx
      - jT9T8_roty
      - jT9T8_rotz
      - jT1C7_rotx
      - jT1C7_roty
      - jT1C7_rotz
      - jC1Head_rotx
      - jC1Head_roty
initial:  # Define initial robot poses per group
  - group: right_arm
    pose: cross_leg_sit
  - group: right_leg
    pose: cross_leg_sit
  - group: left_leg
    pose: cross_leg_sit
  - group: body
    pose: cross_leg_sit