ros_control_namespace: /fanuc_gazebo
controller_list:
  - name: fanuc_gazebo/arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6