// Generated by gencpp from file hierarchial_simulation/lego_pickup.msg
// DO NOT EDIT!


#ifndef HIERARCHIAL_SIMULATION_MESSAGE_LEGO_PICKUP_H
#define HIERARCHIAL_SIMULATION_MESSAGE_LEGO_PICKUP_H

#include <ros/service_traits.h>


#include <hierarchial_simulation/lego_pickupRequest.h>
#include <hierarchial_simulation/lego_pickupResponse.h>


namespace hierarchial_simulation
{

struct lego_pickup
{

typedef lego_pickupRequest Request;
typedef lego_pickupResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct lego_pickup
} // namespace hierarchial_simulation


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::hierarchial_simulation::lego_pickup > {
  static const char* value()
  {
    return "054657831fad2fea203e93682e8ffae0";
  }

  static const char* value(const ::hierarchial_simulation::lego_pickup&) { return value(); }
};

template<>
struct DataType< ::hierarchial_simulation::lego_pickup > {
  static const char* value()
  {
    return "hierarchial_simulation/lego_pickup";
  }

  static const char* value(const ::hierarchial_simulation::lego_pickup&) { return value(); }
};


// service_traits::MD5Sum< ::hierarchial_simulation::lego_pickupRequest> should match
// service_traits::MD5Sum< ::hierarchial_simulation::lego_pickup >
template<>
struct MD5Sum< ::hierarchial_simulation::lego_pickupRequest>
{
  static const char* value()
  {
    return MD5Sum< ::hierarchial_simulation::lego_pickup >::value();
  }
  static const char* value(const ::hierarchial_simulation::lego_pickupRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::hierarchial_simulation::lego_pickupRequest> should match
// service_traits::DataType< ::hierarchial_simulation::lego_pickup >
template<>
struct DataType< ::hierarchial_simulation::lego_pickupRequest>
{
  static const char* value()
  {
    return DataType< ::hierarchial_simulation::lego_pickup >::value();
  }
  static const char* value(const ::hierarchial_simulation::lego_pickupRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::hierarchial_simulation::lego_pickupResponse> should match
// service_traits::MD5Sum< ::hierarchial_simulation::lego_pickup >
template<>
struct MD5Sum< ::hierarchial_simulation::lego_pickupResponse>
{
  static const char* value()
  {
    return MD5Sum< ::hierarchial_simulation::lego_pickup >::value();
  }
  static const char* value(const ::hierarchial_simulation::lego_pickupResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::hierarchial_simulation::lego_pickupResponse> should match
// service_traits::DataType< ::hierarchial_simulation::lego_pickup >
template<>
struct DataType< ::hierarchial_simulation::lego_pickupResponse>
{
  static const char* value()
  {
    return DataType< ::hierarchial_simulation::lego_pickup >::value();
  }
  static const char* value(const ::hierarchial_simulation::lego_pickupResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HIERARCHIAL_SIMULATION_MESSAGE_LEGO_PICKUP_H
