// Generated by gencpp from file hierarchial_simulation/robot_action.msg
// DO NOT EDIT!


#ifndef HIERARCHIAL_SIMULATION_MESSAGE_ROBOT_ACTION_H
#define HIERARCHIAL_SIMULATION_MESSAGE_ROBOT_ACTION_H

#include <ros/service_traits.h>


#include <hierarchial_simulation/robot_actionRequest.h>
#include <hierarchial_simulation/robot_actionResponse.h>


namespace hierarchial_simulation
{

struct robot_action
{

typedef robot_actionRequest Request;
typedef robot_actionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct robot_action
} // namespace hierarchial_simulation


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::hierarchial_simulation::robot_action > {
  static const char* value()
  {
    return "19a560c38819713863fdccb541e95a18";
  }

  static const char* value(const ::hierarchial_simulation::robot_action&) { return value(); }
};

template<>
struct DataType< ::hierarchial_simulation::robot_action > {
  static const char* value()
  {
    return "hierarchial_simulation/robot_action";
  }

  static const char* value(const ::hierarchial_simulation::robot_action&) { return value(); }
};


// service_traits::MD5Sum< ::hierarchial_simulation::robot_actionRequest> should match
// service_traits::MD5Sum< ::hierarchial_simulation::robot_action >
template<>
struct MD5Sum< ::hierarchial_simulation::robot_actionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::hierarchial_simulation::robot_action >::value();
  }
  static const char* value(const ::hierarchial_simulation::robot_actionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::hierarchial_simulation::robot_actionRequest> should match
// service_traits::DataType< ::hierarchial_simulation::robot_action >
template<>
struct DataType< ::hierarchial_simulation::robot_actionRequest>
{
  static const char* value()
  {
    return DataType< ::hierarchial_simulation::robot_action >::value();
  }
  static const char* value(const ::hierarchial_simulation::robot_actionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::hierarchial_simulation::robot_actionResponse> should match
// service_traits::MD5Sum< ::hierarchial_simulation::robot_action >
template<>
struct MD5Sum< ::hierarchial_simulation::robot_actionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::hierarchial_simulation::robot_action >::value();
  }
  static const char* value(const ::hierarchial_simulation::robot_actionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::hierarchial_simulation::robot_actionResponse> should match
// service_traits::DataType< ::hierarchial_simulation::robot_action >
template<>
struct DataType< ::hierarchial_simulation::robot_actionResponse>
{
  static const char* value()
  {
    return DataType< ::hierarchial_simulation::robot_action >::value();
  }
  static const char* value(const ::hierarchial_simulation::robot_actionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HIERARCHIAL_SIMULATION_MESSAGE_ROBOT_ACTION_H
