// Generated by gencpp from file hierarchial_simulation/robot_actionResponse.msg
// DO NOT EDIT!


#ifndef HIERARCHIAL_SIMULATION_MESSAGE_ROBOT_ACTIONRESPONSE_H
#define HIERARCHIAL_SIMULATION_MESSAGE_ROBOT_ACTIONRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hierarchial_simulation
{
template <class ContainerAllocator>
struct robot_actionResponse_
{
  typedef robot_actionResponse_<ContainerAllocator> Type;

  robot_actionResponse_()
    : finished(false)  {
    }
  robot_actionResponse_(const ContainerAllocator& _alloc)
    : finished(false)  {
  (void)_alloc;
    }



   typedef uint8_t _finished_type;
  _finished_type finished;





  typedef boost::shared_ptr< ::hierarchial_simulation::robot_actionResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hierarchial_simulation::robot_actionResponse_<ContainerAllocator> const> ConstPtr;

}; // struct robot_actionResponse_

typedef ::hierarchial_simulation::robot_actionResponse_<std::allocator<void> > robot_actionResponse;

typedef boost::shared_ptr< ::hierarchial_simulation::robot_actionResponse > robot_actionResponsePtr;
typedef boost::shared_ptr< ::hierarchial_simulation::robot_actionResponse const> robot_actionResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hierarchial_simulation::robot_actionResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hierarchial_simulation::robot_actionResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hierarchial_simulation::robot_actionResponse_<ContainerAllocator1> & lhs, const ::hierarchial_simulation::robot_actionResponse_<ContainerAllocator2> & rhs)
{
  return lhs.finished == rhs.finished;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hierarchial_simulation::robot_actionResponse_<ContainerAllocator1> & lhs, const ::hierarchial_simulation::robot_actionResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hierarchial_simulation

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::hierarchial_simulation::robot_actionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hierarchial_simulation::robot_actionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hierarchial_simulation::robot_actionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hierarchial_simulation::robot_actionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hierarchial_simulation::robot_actionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hierarchial_simulation::robot_actionResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hierarchial_simulation::robot_actionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e2797c797e620a950ba704492d72873b";
  }

  static const char* value(const ::hierarchial_simulation::robot_actionResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe2797c797e620a95ULL;
  static const uint64_t static_value2 = 0x0ba704492d72873bULL;
};

template<class ContainerAllocator>
struct DataType< ::hierarchial_simulation::robot_actionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hierarchial_simulation/robot_actionResponse";
  }

  static const char* value(const ::hierarchial_simulation::robot_actionResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hierarchial_simulation::robot_actionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool finished\n"
;
  }

  static const char* value(const ::hierarchial_simulation::robot_actionResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hierarchial_simulation::robot_actionResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.finished);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct robot_actionResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hierarchial_simulation::robot_actionResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hierarchial_simulation::robot_actionResponse_<ContainerAllocator>& v)
  {
    s << indent << "finished: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.finished);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HIERARCHIAL_SIMULATION_MESSAGE_ROBOT_ACTIONRESPONSE_H
