// Generated by gencpp from file moveit_human_config/robot_action.msg
// DO NOT EDIT!


#ifndef MOVEIT_HUMAN_CONFIG_MESSAGE_ROBOT_ACTION_H
#define MOVEIT_HUMAN_CONFIG_MESSAGE_ROBOT_ACTION_H

#include <ros/service_traits.h>


#include <moveit_human_config/robot_actionRequest.h>
#include <moveit_human_config/robot_actionResponse.h>


namespace moveit_human_config
{

struct robot_action
{

typedef robot_actionRequest Request;
typedef robot_actionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct robot_action
} // namespace moveit_human_config


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::moveit_human_config::robot_action > {
  static const char* value()
  {
    return "19a560c38819713863fdccb541e95a18";
  }

  static const char* value(const ::moveit_human_config::robot_action&) { return value(); }
};

template<>
struct DataType< ::moveit_human_config::robot_action > {
  static const char* value()
  {
    return "moveit_human_config/robot_action";
  }

  static const char* value(const ::moveit_human_config::robot_action&) { return value(); }
};


// service_traits::MD5Sum< ::moveit_human_config::robot_actionRequest> should match
// service_traits::MD5Sum< ::moveit_human_config::robot_action >
template<>
struct MD5Sum< ::moveit_human_config::robot_actionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::moveit_human_config::robot_action >::value();
  }
  static const char* value(const ::moveit_human_config::robot_actionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::moveit_human_config::robot_actionRequest> should match
// service_traits::DataType< ::moveit_human_config::robot_action >
template<>
struct DataType< ::moveit_human_config::robot_actionRequest>
{
  static const char* value()
  {
    return DataType< ::moveit_human_config::robot_action >::value();
  }
  static const char* value(const ::moveit_human_config::robot_actionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::moveit_human_config::robot_actionResponse> should match
// service_traits::MD5Sum< ::moveit_human_config::robot_action >
template<>
struct MD5Sum< ::moveit_human_config::robot_actionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::moveit_human_config::robot_action >::value();
  }
  static const char* value(const ::moveit_human_config::robot_actionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::moveit_human_config::robot_actionResponse> should match
// service_traits::DataType< ::moveit_human_config::robot_action >
template<>
struct DataType< ::moveit_human_config::robot_actionResponse>
{
  static const char* value()
  {
    return DataType< ::moveit_human_config::robot_action >::value();
  }
  static const char* value(const ::moveit_human_config::robot_actionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOVEIT_HUMAN_CONFIG_MESSAGE_ROBOT_ACTION_H
