// Generated by gencpp from file stmotion_controller/lego_pickup.msg
// DO NOT EDIT!


#ifndef STMOTION_CONTROLLER_MESSAGE_LEGO_PICKUP_H
#define STMOTION_CONTROLLER_MESSAGE_LEGO_PICKUP_H

#include <ros/service_traits.h>


#include <stmotion_controller/lego_pickupRequest.h>
#include <stmotion_controller/lego_pickupResponse.h>


namespace stmotion_controller
{

struct lego_pickup
{

typedef lego_pickupRequest Request;
typedef lego_pickupResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct lego_pickup
} // namespace stmotion_controller


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::stmotion_controller::lego_pickup > {
  static const char* value()
  {
    return "054657831fad2fea203e93682e8ffae0";
  }

  static const char* value(const ::stmotion_controller::lego_pickup&) { return value(); }
};

template<>
struct DataType< ::stmotion_controller::lego_pickup > {
  static const char* value()
  {
    return "stmotion_controller/lego_pickup";
  }

  static const char* value(const ::stmotion_controller::lego_pickup&) { return value(); }
};


// service_traits::MD5Sum< ::stmotion_controller::lego_pickupRequest> should match
// service_traits::MD5Sum< ::stmotion_controller::lego_pickup >
template<>
struct MD5Sum< ::stmotion_controller::lego_pickupRequest>
{
  static const char* value()
  {
    return MD5Sum< ::stmotion_controller::lego_pickup >::value();
  }
  static const char* value(const ::stmotion_controller::lego_pickupRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::stmotion_controller::lego_pickupRequest> should match
// service_traits::DataType< ::stmotion_controller::lego_pickup >
template<>
struct DataType< ::stmotion_controller::lego_pickupRequest>
{
  static const char* value()
  {
    return DataType< ::stmotion_controller::lego_pickup >::value();
  }
  static const char* value(const ::stmotion_controller::lego_pickupRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::stmotion_controller::lego_pickupResponse> should match
// service_traits::MD5Sum< ::stmotion_controller::lego_pickup >
template<>
struct MD5Sum< ::stmotion_controller::lego_pickupResponse>
{
  static const char* value()
  {
    return MD5Sum< ::stmotion_controller::lego_pickup >::value();
  }
  static const char* value(const ::stmotion_controller::lego_pickupResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::stmotion_controller::lego_pickupResponse> should match
// service_traits::DataType< ::stmotion_controller::lego_pickup >
template<>
struct DataType< ::stmotion_controller::lego_pickupResponse>
{
  static const char* value()
  {
    return DataType< ::stmotion_controller::lego_pickup >::value();
  }
  static const char* value(const ::stmotion_controller::lego_pickupResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // STMOTION_CONTROLLER_MESSAGE_LEGO_PICKUP_H
