// Generated by gencpp from file stmotion_controller/robot_action.msg
// DO NOT EDIT!


#ifndef STMOTION_CONTROLLER_MESSAGE_ROBOT_ACTION_H
#define STMOTION_CONTROLLER_MESSAGE_ROBOT_ACTION_H

#include <ros/service_traits.h>


#include <stmotion_controller/robot_actionRequest.h>
#include <stmotion_controller/robot_actionResponse.h>


namespace stmotion_controller
{

struct robot_action
{

typedef robot_actionRequest Request;
typedef robot_actionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct robot_action
} // namespace stmotion_controller


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::stmotion_controller::robot_action > {
  static const char* value()
  {
    return "19a560c38819713863fdccb541e95a18";
  }

  static const char* value(const ::stmotion_controller::robot_action&) { return value(); }
};

template<>
struct DataType< ::stmotion_controller::robot_action > {
  static const char* value()
  {
    return "stmotion_controller/robot_action";
  }

  static const char* value(const ::stmotion_controller::robot_action&) { return value(); }
};


// service_traits::MD5Sum< ::stmotion_controller::robot_actionRequest> should match
// service_traits::MD5Sum< ::stmotion_controller::robot_action >
template<>
struct MD5Sum< ::stmotion_controller::robot_actionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::stmotion_controller::robot_action >::value();
  }
  static const char* value(const ::stmotion_controller::robot_actionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::stmotion_controller::robot_actionRequest> should match
// service_traits::DataType< ::stmotion_controller::robot_action >
template<>
struct DataType< ::stmotion_controller::robot_actionRequest>
{
  static const char* value()
  {
    return DataType< ::stmotion_controller::robot_action >::value();
  }
  static const char* value(const ::stmotion_controller::robot_actionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::stmotion_controller::robot_actionResponse> should match
// service_traits::MD5Sum< ::stmotion_controller::robot_action >
template<>
struct MD5Sum< ::stmotion_controller::robot_actionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::stmotion_controller::robot_action >::value();
  }
  static const char* value(const ::stmotion_controller::robot_actionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::stmotion_controller::robot_actionResponse> should match
// service_traits::DataType< ::stmotion_controller::robot_action >
template<>
struct DataType< ::stmotion_controller::robot_actionResponse>
{
  static const char* value()
  {
    return DataType< ::stmotion_controller::robot_action >::value();
  }
  static const char* value(const ::stmotion_controller::robot_actionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // STMOTION_CONTROLLER_MESSAGE_ROBOT_ACTION_H
