// Generated by gencpp from file moveit_fanuc_config/robot_actionRequest.msg
// DO NOT EDIT!


#ifndef MOVEIT_FANUC_CONFIG_MESSAGE_ROBOT_ACTIONREQUEST_H
#define MOVEIT_FANUC_CONFIG_MESSAGE_ROBOT_ACTIONREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/PoseStamped.h>
#include <geometry_msgs/PoseStamped.h>

namespace moveit_fanuc_config
{
template <class ContainerAllocator>
struct robot_actionRequest_
{
  typedef robot_actionRequest_<ContainerAllocator> Type;

  robot_actionRequest_()
    : des()
    , src()  {
    }
  robot_actionRequest_(const ContainerAllocator& _alloc)
    : des(_alloc)
    , src(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::PoseStamped_<ContainerAllocator>  _des_type;
  _des_type des;

   typedef  ::geometry_msgs::PoseStamped_<ContainerAllocator>  _src_type;
  _src_type src;





  typedef boost::shared_ptr< ::moveit_fanuc_config::robot_actionRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::moveit_fanuc_config::robot_actionRequest_<ContainerAllocator> const> ConstPtr;

}; // struct robot_actionRequest_

typedef ::moveit_fanuc_config::robot_actionRequest_<std::allocator<void> > robot_actionRequest;

typedef boost::shared_ptr< ::moveit_fanuc_config::robot_actionRequest > robot_actionRequestPtr;
typedef boost::shared_ptr< ::moveit_fanuc_config::robot_actionRequest const> robot_actionRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::moveit_fanuc_config::robot_actionRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::moveit_fanuc_config::robot_actionRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::moveit_fanuc_config::robot_actionRequest_<ContainerAllocator1> & lhs, const ::moveit_fanuc_config::robot_actionRequest_<ContainerAllocator2> & rhs)
{
  return lhs.des == rhs.des &&
    lhs.src == rhs.src;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::moveit_fanuc_config::robot_actionRequest_<ContainerAllocator1> & lhs, const ::moveit_fanuc_config::robot_actionRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace moveit_fanuc_config

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::moveit_fanuc_config::robot_actionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::moveit_fanuc_config::robot_actionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::moveit_fanuc_config::robot_actionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::moveit_fanuc_config::robot_actionRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::moveit_fanuc_config::robot_actionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::moveit_fanuc_config::robot_actionRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::moveit_fanuc_config::robot_actionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4c3cb3bfc4ebe0aeb938436ad71e3af2";
  }

  static const char* value(const ::moveit_fanuc_config::robot_actionRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4c3cb3bfc4ebe0aeULL;
  static const uint64_t static_value2 = 0xb938436ad71e3af2ULL;
};

template<class ContainerAllocator>
struct DataType< ::moveit_fanuc_config::robot_actionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "moveit_fanuc_config/robot_actionRequest";
  }

  static const char* value(const ::moveit_fanuc_config::robot_actionRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::moveit_fanuc_config::robot_actionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/PoseStamped des\n"
"geometry_msgs/PoseStamped src\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseStamped\n"
"# A Pose with reference coordinate frame and timestamp\n"
"Header header\n"
"Pose pose\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::moveit_fanuc_config::robot_actionRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::moveit_fanuc_config::robot_actionRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.des);
      stream.next(m.src);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct robot_actionRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::moveit_fanuc_config::robot_actionRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::moveit_fanuc_config::robot_actionRequest_<ContainerAllocator>& v)
  {
    s << indent << "des: ";
    s << std::endl;
    Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.des);
    s << indent << "src: ";
    s << std::endl;
    Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.src);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOVEIT_FANUC_CONFIG_MESSAGE_ROBOT_ACTIONREQUEST_H
